databases:
  - name: ashwamedh-db
    databaseName: ashwamedh
    user: ashwamedh_user
    plan: free

services:
  - type: web
    name: ashwamedh-lms
    env: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ashwamedh-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ashwamedh-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ashwamedh-db
          property: database
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_USERNAME
        fromDatabase:
          name: ashwamedh-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ashwamedh-db
          property: password
